// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: Mytest.proto

package grpc_go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MytestClient is the client API for Mytest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MytestClient interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloworldRequest, opts ...grpc.CallOption) (*HelloworldResponse, error)
}

type mytestClient struct {
	cc grpc.ClientConnInterface
}

func NewMytestClient(cc grpc.ClientConnInterface) MytestClient {
	return &mytestClient{cc}
}

func (c *mytestClient) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/org.test.Mytest/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mytestClient) Helloworld(ctx context.Context, in *HelloworldRequest, opts ...grpc.CallOption) (*HelloworldResponse, error) {
	out := new(HelloworldResponse)
	err := c.cc.Invoke(ctx, "/org.test.Mytest/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MytestServer is the server API for Mytest service.
// All implementations must embed UnimplementedMytestServer
// for forward compatibility
type MytestServer interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloworldRequest) (*HelloworldResponse, error)
	mustEmbedUnimplementedMytestServer()
}

// UnimplementedMytestServer must be embedded to have forward compatible implementations.
type UnimplementedMytestServer struct {
}

func (UnimplementedMytestServer) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedMytestServer) Helloworld(context.Context, *HelloworldRequest) (*HelloworldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedMytestServer) mustEmbedUnimplementedMytestServer() {}

// UnsafeMytestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MytestServer will
// result in compilation errors.
type UnsafeMytestServer interface {
	mustEmbedUnimplementedMytestServer()
}

func RegisterMytestServer(s grpc.ServiceRegistrar, srv MytestServer) {
	s.RegisterService(&Mytest_ServiceDesc, srv)
}

func _Mytest_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MytestServer).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.test.Mytest/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MytestServer).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mytest_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloworldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MytestServer).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.test.Mytest/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MytestServer).Helloworld(ctx, req.(*HelloworldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mytest_ServiceDesc is the grpc.ServiceDesc for Mytest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mytest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.test.Mytest",
	HandlerType: (*MytestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _Mytest_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _Mytest_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Mytest.proto",
}
